USE [FullDev]
GO

/****** Object: SqlProcedure [dbo].[SPC_LOGIN] Script Date: 29/04/2025 23:01:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE SPC_LOGIN
    @Email VARCHAR(255),
    @Password VARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

     SELECT 
        U.CD_USUARIO, 
        U.EMAIL,
        U.TELEFONE, 
        U.ENDERECO, 
        U.NOME, 
        U.SOBRENOME,
		GU.CD_GRUPO,
		G.NM_GRUPO
    FROM USUARIOS U
	INNER JOIN GRUPO_USUARIO GU ON GU.CD_USUARIO = U.CD_USUARIO
	INNER JOIN GRUPO G ON G.CD_GRUPO = GU.CD_GRUPO
    WHERE U.EMAIL = @Email
      AND U.PASSWORD = @Password;
END;
